
export const person = [
     {
        id: '1',
        img:'/assets/person1.png',
        colors:'#FCEEDF',
     },
     {
        id: '2',
        img:'/assets/person2.png',
        colors:'#FFD3E1',
     },
     {
        id: '3',
        img:'/assets/person3.png',
         colors:'#BDF1E5',
     },
     {
        id: '4',
        img:'/assets/person4.png',
         colors:'#FBECC0',
     },
     {
        id: '5',
        img:'/assets/person5.png',
         colors:'#FCEEDF',
     },
     {
        id: '6',
        img:'/assets/person6.png',
         colors:'#FFD3E1',
     },
];

export const mentors = [
    {
        id:'7',
        img: '/assets/mentor1.png',
        colors: '#FCEEDF',
        name: 'Manoj',
        role: 'Software Engineer',
        caption1: 'Fullstack',
        caption2: 'UI/UX Designer',
        caption3: 'Canva',
    },
     {
        id:'8',
        img: '/assets/mentor2.png',
        colors: '#BDF1E5',
        name: 'Akash',
        role: 'UI/UX Designer',
        caption1: 'Photoshop',
        caption2: 'Illustrator',
        caption3: 'Canva',
    },
     {
        id:'9',
        img: '/assets/mentor3.png',
        colors: '#FBECC0',
        name: 'Hari Haran',
        role: 'Software Engineer',
        caption1: 'Fullstack',
        caption2: 'Node js',
        caption3: 'AOS',
    },
     {
        id:'10',
        img: '/assets/mentor4.png',
        colors: '#FFD3E1',
        name: 'Manirathanam',
        role: 'App Developer',
        caption1: 'Flutter',
        caption2: 'Express js',
        caption3: 'Canva',
    },
     {
        id:'11',
        img: '/assets/mentor5.png',
        colors: '#FCEEDF',
        name: 'Chandru',
        role: 'IOS Developer',
        caption1: 'IOS',
        caption2: 'Apple',
        caption3: 'Canva',
    },
     {
        id:'12',
        img: '/assets/mentor6.png',
        colors: '#BDF1E5',
        name: 'Krishna Prabhu',
        role: 'Frontend Developer',
        caption1: 'Javascript',
        caption2: 'AOS',
        caption3: 'Canva',
    },
   {
        id:'13',
        img: '/assets/mentor7.png',
        colors: '#FBECC0',
        name: 'Vishal',
        role: 'Design Engineer',
        caption1: 'Figma',
        caption2: 'UI/UX Designer',
        caption3: 'Canva'
    },
     {
        id:'14',
        img: '/assets/mentor8.png',
        colors: '#FCEEDF',
        name: 'Hari',
        role: 'Video Editor',
        caption1: 'Capcut',
        caption2: 'VN',
        caption3: 'Kinemaster',
    },
]